/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_knowrob_gaussian_MixedGaussianInterface */

#ifndef _Included_org_knowrob_gaussian_MixedGaussianInterface
#define _Included_org_knowrob_gaussian_MixedGaussianInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_knowrob_gaussian_MixedGaussianInterface
 * Method:    createMixedGaussians
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_knowrob_gaussian_MixedGaussianInterface_createMixedGaussians
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_knowrob_gaussian_MixedGaussianInterface
 * Method:    createMultiVarGaussians
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_knowrob_gaussian_MixedGaussianInterface_createMultiVarGaussians
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_knowrob_gaussian_MixedGaussianInterface
 * Method:    analyzeCluster
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_knowrob_gaussian_MixedGaussianInterface_analyzeCluster
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
